[package]
name = "airdrop2"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "3.0.0"
solana-client = "3.0.3"
solana-program = "3.0.0"
solana-system-interface = "2.0.0"
bs58 = "0.5.1"
dotenv = "0.15.0"
